delivery_fees = [
    { "state": "Abia", "fee": 2500 },
    { "state": "Adamawa", "fee": 3000 },
    { "state": "Akwa Ibom", "fee": 2800 },
    { "state": "Anambra", "fee": 2500 },
    { "state": "Bauchi", "fee": 3000 },
    { "state": "Bayelsa", "fee": 2700 },
    { "state": "Benue", "fee": 2800 },
    { "state": "Borno", "fee": 3500 },
    { "state": "Cross River", "fee": 3000 },
    { "state": "Delta", "fee": 2500 },
    { "state": "Ebonyi", "fee": 2700 },
    { "state": "Edo", "fee": 2200 },
    { "state": "Ekiti", "fee": 2000 },
    { "state": "Enugu", "fee": 2600 },
    { "state": "Gombe", "fee": 3200 },
    { "state": "Imo", "fee": 2500 },
    { "state": "Jigawa", "fee": 3000 },
    { "state": "Kaduna", "fee": 2700 },
    { "state": "Kano", "fee": 2700 },
    { "state": "Katsina", "fee": 2900 },
    { "state": "Kebbi", "fee": 3000 },
    { "state": "Kogi", "fee": 2300 },
    { "state": "Kwara", "fee": 2200 },
    { "state": "Lagos", "fee": 1500 },
    { "state": "Nasarawa", "fee": 2500 },
    { "state": "Niger", "fee": 2600 },
    { "state": "Ogun", "fee": 1800 },
    { "state": "Ondo", "fee": 1500 },
    { "state": "Osun", "fee": 2000 },
    { "state": "Oyo", "fee": 2000 },
    { "state": "Plateau", "fee": 2800 },
    { "state": "Rivers", "fee": 2500 },
    { "state": "Sokoto", "fee": 3200 },
    { "state": "Taraba", "fee": 3100 },
    { "state": "Yobe", "fee": 3300 },
    { "state": "Zamfara", "fee": 3000 },
    { "state": "FCT", "fee": 2200 }
]

DELIVERY_FEES = {item["state"]: item["fee"] for item in delivery_fees}