# Generated by Django 5.1.6 on 2025-10-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
