# Generated by Django 5.2.7 on 2025-10-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aso.cart'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Specific users who have access to this feature when enabled.', related_name='feature_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lookup',
            index=models.Index(fields=['name'], name='aso_lookup_name_1ab83f_idx'),
        ),
        migrations.AddIndex(
            model_name='lookup',
            index=models.Index(fields=['category'], name='aso_lookup_categor_f14155_idx'),
        ),
        migrations.AddIndex(
            model_name='lookup',
            index=models.Index(fields=['is_deleted'], name='aso_lookup_is_dele_040d52_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aso.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aso.order'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_product', to='aso.order'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='aso.order'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='aso.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='aso.lookup'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aso.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aso.product'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='aso.product'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='aso.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aso.product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='aso.product'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='aso.order'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_product', to='aso.product'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='aso_cart_user_id_0eb08a_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['state'], name='aso_cart_state_bc555f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted'], name='aso_cart_is_dele_9fb74d_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_enabled'], name='aso_feature_is_enab_784620_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='aso_order_order_n_4c90e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='aso_order_user_id_3b0cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='aso_order_created_ae8b55_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfeedback',
            index=models.Index(fields=['order'], name='aso_orderfe_order_i_c8f5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order'], name='aso_orderre_order_i_476a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['order', 'status', 'date'], name='aso_ordertr_order_i_77d05d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordertracking',
            unique_together={('status', 'order')},
        ),
        migrations.AddIndex(
            model_name='paymentdetail',
            index=models.Index(fields=['method'], name='aso_payment_method_84bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='aso_product_title_7a7411_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_price'], name='aso_product_current_bc009b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='aso_product_product_2cb28f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['id'], name='product_not_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='aso_orderit_order_i_12242a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='aso_cartite_cart_id_3b58a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='productcolor',
            index=models.Index(fields=['product', 'color_name'], name='aso_product_product_8c17a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color_name')},
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['product', 'tab'], name='aso_product_product_cf63c2_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='aso_product_product_062509_idx'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['product', 'size_label'], name='aso_product_product_28a8df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size_label')},
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'state'], name='aso_shippin_city_6c7571_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'product')},
        ),
    ]
