# Generated by Django 5.1 on 2025-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="discount_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
