# Generated by Django 5.1.6 on 2025-10-21 22:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0003_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='aso_cartite_cart_id_23c3a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='aso_cartite_product_cd3879_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='aso_orderit_order_i_577782_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='aso_orderit_product_cc743f_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['state'], name='aso_cart_state_bc555f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted'], name='aso_cart_is_dele_9fb74d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='aso_cartite_cart_id_3b58a3_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_enabled'], name='aso_feature_is_enab_784620_idx'),
        ),
        migrations.AddIndex(
            model_name='lookup',
            index=models.Index(fields=['name'], name='aso_lookup_name_1ab83f_idx'),
        ),
        migrations.AddIndex(
            model_name='lookup',
            index=models.Index(fields=['category'], name='aso_lookup_categor_f14155_idx'),
        ),
        migrations.AddIndex(
            model_name='lookup',
            index=models.Index(fields=['is_deleted'], name='aso_lookup_is_dele_040d52_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='aso_order_created_ae8b55_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfeedback',
            index=models.Index(fields=['order'], name='aso_orderfe_order_i_c8f5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='aso_orderit_order_i_12242a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order'], name='aso_orderre_order_i_476a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['order', 'status', 'date'], name='aso_ordertr_order_i_77d05d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdetail',
            index=models.Index(fields=['method'], name='aso_payment_method_84bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='aso_product_product_2cb28f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['id'], name='product_not_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='productcolor',
            index=models.Index(fields=['product', 'color_name'], name='aso_product_product_8c17a6_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['product', 'tab'], name='aso_product_product_cf63c2_idx'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['product', 'size_label'], name='aso_product_product_28a8df_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'state'], name='aso_shippin_city_6c7571_idx'),
        ),
    ]
