# Generated by Django 5.1 on 2025-11-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0003_featureflag_count_featureflag_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_limited",
            field=models.BooleanField(default=False),
        ),
    ]
