# Generated by Django 5.1 on 2025-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0004_featureflag_is_active_product_is_limited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="name",
            field=models.CharField(
                choices=[
                    ("Promo Banner", "Promo Banner"),
                    ("Referral System", "Referral System"),
                    ("Free Delivery", "Free Delivery"),
                    ("Cart Discount", "Cart Discount"),
                    ("Black Friday", "Black Friday"),
                    ("Product Limitation", "Product Limitation"),
                    ("New Product Announcement", "New Product Announcement"),
                    ("Background Tasks", "Background Tasks"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
