# Generated by Django 5.1 on 2025-11-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0005_alter_featureflag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="telegram_user_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
