# Generated by Django 5.1 on 2025-11-28 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0006_order_telegram_user_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="name",
            field=models.CharField(
                choices=[
                    ("Promo Banner", "Promo Banner"),
                    ("Referral System", "Referral System"),
                    ("Free Delivery", "Free Delivery"),
                    ("Cart Discount", "Cart Discount"),
                    ("Black Friday", "Black Friday"),
                    ("Product Limitation", "Product Limitation"),
                    ("New Product Announcement", "New Product Announcement"),
                    ("Background Tasks", "Background Tasks"),
                    ("Feedback", "Feedback"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, "Rating must be at least 0.0"
                    ),
                    django.core.validators.MaxValueValidator(
                        5.0, "Rating cannot be greater than 5.0 stars"
                    ),
                ],
            ),
        ),
    ]
