# Generated by Django 5.1 on 2025-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0007_alter_featureflag_name_alter_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetail",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
