# Generated by Django 5.1 on 2025-12-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0008_paymentdetail_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="telegram_user_chat_id",
        ),
    ]
