# Generated by Django 5.1 on 2026-01-01 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0011_recentsearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertracking",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ordertracking",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
