# Generated by Django 5.0.2 on 2026-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0012_alter_ordertracking_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Cart is locked during payment processing. Prevents user modifications.",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("failed", "Payment Failed"),
                    ("confirmed", "Payment Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
