# Generated by Django 5.0.2 on 2026-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aso", "0014_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="locked",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("system", "system"),
                    ("updates", "updates"),
                    ("promos", "promos"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordertracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("placed", "placed"),
                    ("processing", "processing"),
                    ("shipped", "shipped"),
                    ("in_transit", "in_transit"),
                    ("delivered", "delivered"),
                    ("cancelled", "cancelled"),
                ],
                default="placed",
                max_length=20,
            ),
        ),
    ]
