# Generated by Django 5.1.6 on 2025-10-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_referral_qualified_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_used',
            field=models.BooleanField(default=False),
        ),
    ]
