# Generated by Django 5.2.7 on 2025-11-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
