# Generated by Django 5.1.6 on 2025-10-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_referral_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_used_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
