# Generated by Django 5.1 on 2025-11-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_transaction_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=5000)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["-id"], name="users_conta_id_0e77cb_idx")
                ],
            },
        ),
    ]
