# Generated by Django 5.1 on 2025-11-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_contactformsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformsubmission",
            name="status",
            field=models.CharField(
                choices=[("New", "New"), ("Replied", "Replied")],
                default="New",
                max_length=50,
            ),
        ),
    ]
