# Generated by Django 5.1 on 2025-12-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_contactformsubmission_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=100, null=True)),
                ("user_agent_string", models.TextField()),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("os_version", models.CharField(blank=True, max_length=50, null=True)),
                ("device", models.CharField(blank=True, max_length=100, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_seen"],
                        name="users_usera_user_id_b9ebf9_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="users_usera_ip_addr_5734fc_idx"
                    ),
                ],
                "unique_together": {("user", "user_agent_string", "ip_address")},
            },
        ),
    ]
