# Generated by Django 5.1 on 2025-12-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_useragent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_user_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_user_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
