# Generated by Django 5.1.6 on 2025-03-22 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Nigerian number (e.g., 08012345678 or +2348012345678).', regex='^(?:\\+234|0)[789][01]\\d{8}$')]),
        ),
    ]
