# Generated by Django 5.1.6 on 2025-08-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_user_state_code_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
