# Generated by Django 5.1.6 on 2025-08-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_user_phone_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rider_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
