# Generated by Django 5.1.6 on 2025-08-24 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_user_rider_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Nigerian number (e.g., 08012345678 or +2348012345678).', regex='^(?:\\+234|0)[789][01]\\d{8}$')]),
        ),
    ]
