# Generated by Django 5.1.6 on 2025-10-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.CharField(blank=True, choices=[('Promo Banner', 'Promo Banner'), ('Referral System', 'Referral System'), ('Free Delivery', 'Free Delivery'), ('Cart Discount', 'Cart Discount'), ('Black Friday', 'Black Friday')], max_length=100, null=True),
        ),
    ]
