# Generated by Django 5.2.7 on 2025-10-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='administrat_user_e0b05d_idx'), models.Index(fields=['created_at'], name='administrat_created_8a758c_idx')],
            },
        ),
    ]
