# Generated by Django 5.2.7 on 2025-10-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
