# Generated by Django 5.1.6 on 2025-10-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(blank=True, choices=[('Promo', 'Promo'), ('index', 'index'), ('ads', 'ads'), ('support', 'support'), ('black friday', 'black friday'), ('hero', 'hero')], max_length=100, null=True),
        ),
    ]
