# Generated by Django 5.1 on 2025-11-28 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0003_customerfeedback_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerfeedback",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Rating must be at least 1 star"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Rating cannot be greater than 5 stars"
                    ),
                ]
            ),
        ),
    ]
