# Generated by Django 5.1.6 on 2025-03-21 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('fabric_type', models.CharField(choices=[('Aso Oke', 'Aso Oke'), ('Aso Ofi', 'Aso Ofi')], max_length=20)),
                ('color', models.CharField(db_index=True, max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('material', models.CharField(help_text='E.g., Cotton, Silk, Wool', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aso_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('aso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aso.aso')),
            ],
        ),
        migrations.AddField(
            model_name='aso',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asos', to='aso.category'),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('Overnight', 'Overnight')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_days', models.PositiveIntegerField(help_text='Estimated days for delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='aso.aso')),
            ],
            options={
                'ordering': ['shipping_method'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('aso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='aso.aso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='aso.shipping')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddIndex(
            model_name='aso',
            index=models.Index(fields=['name'], name='aso_aso_name_c0e6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='aso',
            index=models.Index(fields=['color'], name='aso_aso_color_11adc1_idx'),
        ),
        migrations.AddIndex(
            model_name='aso',
            index=models.Index(fields=['price'], name='aso_aso_price_096aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['shipping_method'], name='aso_shippin_shippin_a52164_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['cost'], name='aso_shippin_cost_faf4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='aso_order_user_id_3b0cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='aso_order_status_25bf33_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='aso_order_order_d_6d4a94_idx'),
        ),
    ]
