# Generated by Django 5.1.6 on 2025-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0006_product_product_number_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertracking',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='ordertracking',
            unique_together={('status', 'order')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='aso_orderit_order_i_577782_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='aso_orderit_product_cc743f_idx'),
        ),
    ]
