# Generated by Django 5.1.6 on 2025-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0007_alter_ordertracking_options_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_product',
            field=models.BooleanField(default=False),
        ),
    ]
