# Generated by Django 5.1.6 on 2025-08-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0008_product_display_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_product',
            field=models.BooleanField(default=True),
        ),
    ]
