# Generated by Django 5.1.6 on 2025-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0010_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
