# Generated by Django 5.1.6 on 2025-08-09 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0011_cart_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='expiry_date',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'product')},
        ),
    ]
