# Generated by Django 5.1.6 on 2025-08-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0012_remove_paymentdetail_card_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
    ]
