# Generated by Django 5.1.6 on 2025-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0015_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
