# Generated by Django 5.1.6 on 2025-08-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0016_remove_order_completed_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aso.order')),
            ],
        ),
    ]
