# Generated by Django 5.1.6 on 2025-08-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0017_orderfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
