# Generated by Django 5.1.6 on 2025-08-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0018_cartitem_desc_orderitem_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='desc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='desc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
