# Generated by Django 5.1.6 on 2025-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0019_alter_cartitem_desc_alter_orderitem_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
