# Generated by Django 5.1.6 on 2025-08-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0021_orderreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturn',
            name='item',
        ),
    ]
